library(readxl)
kf <- read_excel("C:/Rstudy/한식집_가공.xlsx")
head(kf)
address <- substr(kf$소재지전체주소, 12, 16)
head(address)
address_trim <- gsub(" ","", address)
address_hyphen <- gsub("-","",address_trim)
address_num <- gsub("[0-9]", "", address_hyphen)
head(addr_num)
library(dplyr)
address_count <- address_num %>% table() %>% data.frame()
head(address_count)
install.packages("treemap")
library(treemap)
treemap(address_count, index=".", vSize="Freq", title="팔달구 동별 한식집 분표")
arrange(address_count, desc(Freq)) %>% head()
